server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: anibox
  datasource:
    #这里mysql:3306是docker容器的名称和端口 本地启动换成localhost
    url: jdbc:mysql://mysql:3306/anibox?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  data:
    redis:
      #这里host: redis是docker容器的名称 本地启动换成localhost
      host: redis
      port: 6379
      password: password
      database: 0
#SQL 日志 标准输出在控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
